### ISSUE TITLE
install on centos 7 nodejs 11 fail with errors

### ISSUE THREAD

**Issue by tpimont** [staskobzar/amiws_queue#7]
npm run build

> amiws_queue@1.0.0 build /tmp/amiws_queue
> node build/build.js

/tmp/amiws_queue/node_modules/webpack/lib/webpack.js:185
                        throw new RemovedPluginError(errorMessage);
                        ^

Error: webpack.optimize.UglifyJsPlugin has been removed, please use config.optimization.minimize instead.
    at Object.get [as UglifyJsPlugin] (/tmp/amiws_queue/node_modules/webpack/lib/webpack.js:185:10)
    at Object.<anonymous> (/tmp/amiws_queue/build/webpack.prod.conf.js:36:26)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/tmp/amiws_queue/build/build.js:12:23)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! amiws_queue@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the amiws_queue@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by panjangin** [comment]
Hi, have you got the solution for this error?

**Comment by staskobzar** [comment]
no, unfortunatelly I have not fix it. The problem is probably that the core libs and packages are too old and outdated sot it will take a lot of work to update and I am not sure I have time for it now
sorry

**Comment by panjangin** [comment]
Noted, thank you.
